wallpaper {
    monitor = eDP-1
    path = /home/kopihue/Pictures/Wallpapers/esdeath.png
    fit_mode = cover
}

wallpaper {
    monitor = DP-1
    path = /home/kopihue/Pictures/Wallpapers/esdeath.png
    fit_mode = cover
}

splash = false
